hydra: # hydra 로그 파일 생성 최대한 끄기
  run:
    dir: ./hydra/
  job_logging:
    root:
      handlers: [ ]
    output_subdir: null

project:
  name: "LLMOps RAG 벤치마크 분석"
  version: "v0.0.1"

defaults:
  - _self_
  - llm: upstage
  - embedder: jinav3
  - retriever: naive
  - dataset: case_docs
  - prompt: qa_legal_free
  - evaluation: langsmith
  - evaluation/metrics: metrics

data:
  top_k: 3
  chunk_size: 4000
  chunk_overlap: 400
  law_cases_dir: "data/law"
  # law_cases_dir: "data/dummy"

exp:
  sid: sess_001   # 세션을 위한 임시 변수
  scenario: simple
  temperature: 0.8
  max_tokens: 1024
  make_embedding: True
  question: "취업규칙을 근로자에게 불리하게 변경할 때 사용자가 지켜야 할 법적 요건은 무엇인가요?"
  #  question: "외계인"
  questions: [
    "안녕하세요. 당신은 법률 관련 답변을 할 수 있나요?",
    "어떤 사건을 위해 선임된 변호사는 판결 결과에 대한 책임이 없나요?",
    "직전에 제가 뭐라고 질문을 했었죠?",
    "아까 질문에서 형사적인 책임은 없더라도 패소하였다면 의뢰자가 변호사 비용의 일부만 부담하는 것이 맞지 않나요?",
    "위에서 논의한 내용을 영어로 정리해주세요"
  ]


langsmith:
  enabled: false
  project: "langchain benchmark"
  metadata:
    ver: "2025.08.27"

opts:
  llms: [ "openai", "anthropic", "upstage", "custom", "mock" ]
  datasets: [ "case_docs", "default", "dataframe" ]
  scenarios: [ "simple", "comparison", "demo" ]
  retrievers: [ "naive", "legalQA", "frequency", "bm25", "dense", "hybrid" ]
  prompts: [ "qa_legal", "qa_lega_free" ]




