# @package _global_

# Hydra defaults - 각 카테고리의 기본 설정
defaults:
  - /llm: gemini
  - /embedding: google  
  - /data: base
  - _self_

# LangSmith 설정 (추적 및 모니터링)
langsmith:
  enabled: true
  project_name: "legal-qa-chatbot"
  endpoint: "https://api.smith.langchain.com"

# 벡터 스토어 설정
vector_store:
  type: faiss
  persist_directory: ./faiss_db

# 검색기 설정
retriever:
  type: ensemble # bm25, dense, ensemble 중 선택
  weights: [0.5, 0.5] # ensemble retriever 사용 시 BM25와 Dense retriever의 가중치

# 체인 설정
chain:
  type: retrieval_qa
  retriever_k: 4

# 전처리 설정
preprocessing:
  enabled: true
  filter_case_types: false
  target_case_types: []

# 채팅 히스토리 설정 (QA Engine: 5번 이상 기억)
chat_history:
  max_history: 5
  save_path: "logs/chat_history.json"

# 로깅 설정
logging:
  level: "INFO"
  directory: "logs"

# 대화형 모드 설정
interactive: false

# Hydra 출력 디렉토리 비활성화
hydra:
  job:
    chdir: false
  run:
    dir: .


